### ISSUE TITLE
Multiple links

### ISSUE THREAD

**Issue by JGuetschow** [openclimatedata/national-inventory-submisions#1]
I just tried the downloader and got the following error message:

> Russian Federation NIR 2018	https://unfccc.int/documents/65719	https://unfccc.int/sites/default/files/resource/rus-2018-nir-14apr18.zip
> Traceback (most recent call last):
>   File "scripts/process.py", line 87, in <module>
>     raise ValueError("More than one link found. Please update script"
> ValueError: More than one link found. Please update script to handle multiple links.
> Makefile:2: recipe for target 'data-2018' failed
> make: *** [data-2018] Error 1

The error message suggests that it's known that this might occur at some point and needs development?

**Comment by rgieseke** [comment]
I'll have a look, thanks for the report.

**Comment by rgieseke** [comment]
Pushed a workaround https://github.com/openclimatedata/national-inventory-submisions/commit/15eb48817aae6002056b4a871f5cb37ab41940d0

The note should not download anyway (not matching CRF, NIR ...).

Please re-open if this causes trouble elsewhere.
