### ISSUE TITLE
Download BUR submissions

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/national-inventory-submisions#4]
Automate BUR download should work in similar way as CRF data

Two tasks

```
make data-bur
make download-bur
```
URL:
https://unfccc.int/BURs

**Comment by rgieseke** [comment]
@JGuetschow pushed a first attempt, the kind colum is either BUR{1,2,3} or NIR or NC if it's not easy to parse otherwise. Let me know what you think or need ...

**Comment by JGuetschow** [comment]
Collecting the links (make-bur) works fine and the resulting csv looks good. The actual download is not implemented yet, right? I can't remember if you do that or if I said I would do that to sort downloads into the folders I have for the BUR reading.

**Comment by rgieseke** [comment]
Not yet implemented ... wanted to check with you if you have special ideas for doing that ...

**Comment by JGuetschow** [comment]
Currently I have a folder for each BUR round ("first_BUR_files" for BUR1, "second_BUR_files" for BUR2, "third_BUR_files" for BUR3). In each of the folders there is a folder for each country that has submitted a BUR in that round (so e.g. BUR1/Argentina) which contains all downloaded files (BUR pdf, NIR pdf, etc) and also all data read from the BUR (csv and xls output from tabula and similar tools). But the structure could also be changed in the BUR repository, or we use a script that copies the downloaded data into the right folders (or fork the BUR code from this repo into the BUR repo).

**Comment by JGuetschow** [comment]
But as not too many BURs are submitted, I think copying into the right folder for analysis by hand is also completely feasible. In that case it would just be important, that the additional files (NIR etc) can be associated to their respective BUR.

**Comment by rgieseke** [comment]
For the time being a simple download is probably ok then, i'll add that later ... the diff of the CSV will highlight added files which can be copied into your structure.

**Comment by JGuetschow** [comment]
Sounds good to me

**Comment by rgieseke** [comment]
I've added a basic download script.

Could be improved by creating subdirs by country or making the filenames nicer e.g. by prefixing them.

One can of course use the CSV data to copy from filenames into another structure as well.
